#
#  _____       _                ______            _                 _                        _
# |  __ \     | |              |  ____|          | |               | |                      | |
# | |  | | ___| |_   ___  _____| |__   _ __   ___| |__   __ _ _ __ | |_ _ __ ___   ___ _ __ | |_ ___
# | |  | |/ _ \ | | | \ \/ / _ \  __| | '_ \ / __| '_ \ / _` | '_ \| __| '_ ` _ \ / _ \ '_ \| __/ __|
# | |__| |  __/ | |_| |>  <  __/ |____| | | | (__| | | | (_| | | | | |_| | | | | |  __/ | | | |_\__ \
# |_____/ \___|_|\__,_/_/\_\___|______|_| |_|\___|_| |_|\__,_|_| |_|\__|_| |_| |_|\___|_| |_|\__|___/
#
# Author: FusionCoding
# Version: 1.0
# State: ALPHA
#
General:
 Prefix: "&bDeluxe&7Enchantments \xbb &7"
